sudo: required
cache:
- apt
language: generic

# ros distro
matrix:
  include:
  - name: "Xenial kinetic"
    dist: xenial
    env: ROS_DISTRO=kinetic

# env
env:
  global:
    - ROS_CI_DESKTOP="`lsb_release -cs`"
    - CI_SOURCE_PATH=$(pwd)

script:
  - bash -xve ./test/travis_ros_install.bash

 
